global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: [ 'localhost:9090' ]

remote_write:
  - url: 'http://localhost:9090/api/v1/write'
